version: "3.8"
services:
  db:
    image: mongo:4.2
    container_name: db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db

  react-app:
    build: .
    image: 192.168.33.10:8083/reactapp:1.0
    restart: always
    container_name: react-app
    ports:
      - "8084:8084" # Expose the React development server port
    depends_on:
      - db
volumes:
  mongo-data:
